apiVersion: v1
kind: PersistentVolume
metadata:
  # any PV name
  name: site-staing-nfs-pv
spec:
  capacity:
    # storage size
    storage: 30Gi
  accessModes:
    # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    # retain even if pods terminate
    Retain
  nfs:
    # NFS server's definition
    path: /mnt/nfsshare
    server: 192.168.10.110
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: site-staging-nfs-pvc
spec:
  accessModes:
  # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
  - ReadWriteMany
  resources:
     requests:
       # storage size to use
       storage: 10Gi
